# iTextSharp-basierte PDF Analyse fuer ICPMH Audit Trails
# MSAT Reviewer - ICPMH Edition
# Y-Zeilen erst gruppieren, dann nach Spalten filtern

$ScriptPath = Split-Path -Parent $MyInvocation.MyCommand.Definition
Add-Type -Path (Join-Path $ScriptPath "itextsharp.dll")

# Custom Strategy Class
$customStrategyCode = @"
using System;
using System.Collections.Generic;
using iTextSharp.text.pdf.parser;

public class CoordinateTextExtractionStrategy : ITextExtractionStrategy
{
    public List<TextChunk> TextChunks = new List<TextChunk>();
    
    public void BeginTextBlock() { }
    public void EndTextBlock() { }
    
    public void RenderText(TextRenderInfo renderInfo)
    {
        string text = renderInfo.GetText();
        var baseline = renderInfo.GetBaseline();
        float x = baseline.GetStartPoint()[0];
        float y = baseline.GetStartPoint()[1];
        TextChunks.Add(new TextChunk(text, x, y));
    }
    
    public string GetResultantText() { return ""; }
    public void RenderImage(ImageRenderInfo renderInfo) { }
}

public class TextChunk
{
    public string Text { get; set; }
    public float X { get; set; }
    public float Y { get; set; }
    
    public TextChunk(string text, float x, float y)
    {
        Text = text;
        X = x;
        Y = y;
    }
}
"@

Add-Type -TypeDefinition $customStrategyCode -ReferencedAssemblies (Join-Path $ScriptPath "itextsharp.dll")

$TargetGroups = @("ICPMHAdmin", "ICPMHManager")

Write-Host "=============================================="
Write-Host " MSAT Reviewer - ICPMH Audit Trail Analyzer"
Write-Host " (Y-Zeilen gruppiert)"
Write-Host "=============================================="
Write-Host ""
Write-Host "Filter-Einstellungen:"
Write-Host "  - Groups: $($TargetGroups -join ', ')"
Write-Host "  - Reason: Muss vorhanden sein (ausser 'Autogenerated')"
Write-Host ""

$sortChoice = Read-Host "Sortieren nach Seitenzahl (S) oder User (U)?"
if ($sortChoice -match "^[Uu]") { $SortMode = "User" }
else { $SortMode = "Seitenzahl" }

$ATIN = Join-Path $ScriptPath "AT_IN"
if (-not (Test-Path $ATIN)) {
    Write-Host "AT_IN nicht gefunden. Bitte Ordner auswaehlen..."
    Add-Type -AssemblyName System.Windows.Forms
    $fbd = New-Object System.Windows.Forms.FolderBrowserDialog
    if ($fbd.ShowDialog() -eq "OK") { $ATIN = $fbd.SelectedPath } else { return }
} else {
    $confirm = Read-Host "AT_IN gefunden. PDFs dort analysieren? (J/N)"
    if ($confirm -notmatch "^[Jj]") {
        Add-Type -AssemblyName System.Windows.Forms
        $fbd = New-Object System.Windows.Forms.FolderBrowserDialog
        if ($fbd.ShowDialog() -eq "OK") { $ATIN = $fbd.SelectedPath } else { return }
    }
}

$pdfFiles = Get-ChildItem -Path $ATIN -Filter *.pdf
if (-not $pdfFiles) {
    Write-Host "Keine PDFs im Ordner. Beende..."
    return
}

$ATOUT = Join-Path $ScriptPath "AT_OUT"
if (-not (Test-Path $ATOUT)) { New-Item -Path $ATOUT -ItemType Directory | Out-Null }

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$reportPath = Join-Path $ATOUT "ICPMH_RE$timestamp.txt"
$UserName = $env:USERNAME

# PDF mit Koordinaten extrahieren
function Get-PdfTextChunks {
    param($pdfPath)
    $reader = New-Object iTextSharp.text.pdf.PdfReader -ArgumentList $pdfPath
    $allChunks = @()
    
    for ($i = 1; $i -le $reader.NumberOfPages; $i++) {
        $strategy = New-Object CoordinateTextExtractionStrategy
        [void][iTextSharp.text.pdf.parser.PdfTextExtractor]::GetTextFromPage($reader, $i, $strategy)
        
        foreach ($chunk in $strategy.TextChunks) {
            $allChunks += [pscustomobject]@{
                Page = $i
                X = $chunk.X
                Y = $chunk.Y
                Text = $chunk.Text
            }
        }
    }
    
    $reader.Close()
    return $allChunks
}

# Gruppiere Chunks nach Y-Position (physische Zeilen)
function Group-ChunksByY {
    param($chunks, $yTolerance = 0.5)
    
    $yGroups = @{}
    
    foreach ($chunk in $chunks) {
        $y = $chunk.Y
        $foundGroup = $false
        
        # Suche existierende Y-Gruppe
        foreach ($existingY in $yGroups.Keys) {
            if ([Math]::Abs($y - $existingY) -lt $yTolerance) {
                $yGroups[$existingY] += $chunk
                $foundGroup = $true
                break
            }
        }
        
        # Neue Gruppe erstellen
        if (-not $foundGroup) {
            $yGroups[$y] = @($chunk)
        }
    }
    
    return $yGroups
}

# Parse alle Eintraege
function Parse-AuditEntries {
    param($chunks, $pdfName)
    
    Write-Host ""
    Write-Host "=== PARSING STARTEN ==="
    Write-Host "Chunks gesamt: $($chunks.Count)"
    
    # 1. Finde Header-Zeile
    $yGroups = Group-ChunksByY -chunks $chunks
    $headerY = $null
    
    foreach ($y in ($yGroups.Keys | Sort-Object -Descending)) {
        $yChunks = $yGroups[$y]
        $yText = ($yChunks | Sort-Object X | Select-Object -ExpandProperty Text) -join " "
        
        if ($yText -match "User" -and $yText -match "Group" -and 
            $yText -match "Time" -and $yText -match "Category") {
            $headerY = $y
            Write-Host "Header gefunden bei Y=$([Math]::Round($headerY, 2))"
            break
        }
    }
    
    if (-not $headerY) {
        Write-Host "FEHLER: Kein Header gefunden!"
        return @()
    }
    
    # 2. Extrahiere Spalten-X-Positionen aus Header
    $headerChunks = $chunks | Where-Object { 
        [Math]::Abs($_.Y - $headerY) -lt 2.0 -and
        $_.Text -match "^(User|Group|Time|Succeeded|Category|Reason|Action|Error)"
    } | Sort-Object X
    
    if ($headerChunks.Count -lt 8) {
        Write-Host "FEHLER: Nur $($headerChunks.Count) Spalten gefunden!"
        return @()
    }
    
    $columns = @()
    foreach ($hc in $headerChunks) {
        $columns += [pscustomobject]@{ Name = $hc.Text; X = $hc.X }
    }
    
    Write-Host "Spalten erkannt: $($columns.Count)"
    
    # 3. Finde Tabellenzeilen-Starts (wo User UND Group gleichzeitig gefuellt)
    $tableRowStarts = @()
    $userColX = $columns[0].X
    $groupColX = $columns[1].X
    
    foreach ($y in ($yGroups.Keys | Sort-Object -Descending)) {
        if ($y -ge ($headerY - 10)) { continue }  # Ueberspringe Header
        if ($y -lt -50) { continue }  # Ueberspringe Footer
        
        $yChunks = $yGroups[$y]
        
        # Pruefe ob User-Spalte UND Group-Spalte Text haben
        $hasUser = $yChunks | Where-Object { [Math]::Abs($_.X - $userColX) -lt 5 }
        $hasGroup = $yChunks | Where-Object { [Math]::Abs($_.X - $groupColX) -lt 5 -and $_.Text -match "ICPMH" }
        
        if ($hasUser -and $hasGroup) {
            $tableRowStarts += $y
        }
    }
    
    $tableRowStarts = $tableRowStarts | Sort-Object -Descending
    Write-Host "Tabellenzeilen erkannt: $($tableRowStarts.Count)"
    
    if ($tableRowStarts.Count -eq 0) {
        Write-Host "FEHLER: Keine Tabellenzeilen gefunden!"
        return @()
    }
    
    # 4. Fuer jede Tabellenzeile: Extrahiere Zellen
    $entries = @()
    
    for ($i = 0; $i -lt $tableRowStarts.Count; $i++) {
        $rowStartY = $tableRowStarts[$i]
        $rowEndY = if ($i+1 -lt $tableRowStarts.Count) { $tableRowStarts[$i+1] } else { -100 }
        
        # Hole alle Chunks in diesem Y-Bereich
        $rowChunks = $chunks | Where-Object { $_.Y -le $rowStartY -and $_.Y -gt $rowEndY }
        
        $entry = [ordered]@{
            Page         = ($rowChunks | Select-Object -First 1).Page
            User         = ""
            Group        = ""
            Time         = ""
            Succeeded    = ""
            Category     = ""
            Reason       = ""
            Action       = ""
            ErrorMessage = ""
            SourcePDF    = $pdfName
        }
        
        # Extrahiere jede Spalte
        for ($c = 0; $c -lt $columns.Count; $c++) {
            $colX = $columns[$c].X
            $nextColX = if ($c+1 -lt $columns.Count) { $columns[$c+1].X } else { 1000 }
            
            # Finde Chunks in dieser Spalte
            $colChunks = $rowChunks | Where-Object { 
                $_.X -ge ($colX - 2) -and $_.X -lt $nextColX 
            } | Sort-Object @{Expression="Y"; Descending=$true}, X
            
            $cellText = ($colChunks | Select-Object -ExpandProperty Text) -join " "
            $cellText = $cellText.Trim()
            
            # Zuordnung nach Spaltenname
            $colName = $columns[$c].Name
            if ($colName -eq "User") { $entry.User = $cellText }
            elseif ($colName -eq "Group") { $entry.Group = $cellText }
            elseif ($colName -match "Time") { $entry.Time = $cellText }
            elseif ($colName -eq "Succeeded") { $entry.Succeeded = $cellText }
            elseif ($colName -eq "Category") { $entry.Category = $cellText }
            elseif ($colName -eq "Reason") { $entry.Reason = $cellText }
            elseif ($colName -eq "Action") { $entry.Action = $cellText }
            elseif ($colName -match "Error") { $entry.ErrorMessage = $cellText }
        }
        
        $entries += [pscustomobject]$entry
    }
    
    return $entries
}

# Hauptlogik
Write-Host "Analysiere PDFs..."
$allFindings = @()

foreach ($pdf in $pdfFiles) {
    Write-Host ""
    Write-Host "======================================"
    Write-Host "PDF: $($pdf.Name)"
    Write-Host "======================================"
    
    $chunks = Get-PdfTextChunks -pdfPath $pdf.FullName
    $entries = Parse-AuditEntries -chunks $chunks -pdfName $pdf.Name
    
    Write-Host "Gefundene Eintraege: $($entries.Count)"
    
    foreach ($e in $entries) {
        $groupMatch = $false
        foreach ($tg in $TargetGroups) {
            if ($e.Group -like "*$tg*") { $groupMatch = $true; break }
        }
        
        $reasonValid = (-not [string]::IsNullOrWhiteSpace($e.Reason)) -and 
                       ($e.Reason -ne "Autogenerated")
        
        if ($groupMatch -and $reasonValid) {
            $allFindings += $e
        }
    }
    
    $pdfHits = ($allFindings | Where-Object { $_.SourcePDF -eq $pdf.Name }).Count
    Write-Host "Relevante Findings: $pdfHits"
}

Write-Host ""
Write-Host "======================================"
Write-Host "Gesamtanzahl Findings: $($allFindings.Count)"
Write-Host "======================================"

if ($SortMode -eq "User") {
    $allFindings = $allFindings | Sort-Object User, Time
}
else {
    $allFindings = $allFindings | Sort-Object Page, Time
}

# Report schreiben
$report = @()
$report += "----------------------------------------------------"
$report += " MSAT Review - Analysebericht (ICPMH)"
$report += "----------------------------------------------------"
$report += "Benutzer: $UserName"
$report += "Datum:    $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$report += ""
$report += "Analysierte PDFs: [$($pdfFiles.Name -join ', ')]"
$report += "TOTAL Findings Overall: $($allFindings.Count)"
$report += ""
$report += "Filter-Kriterien:"
$report += "  - Groups: $($TargetGroups -join ', ')"
$report += "  - Reason: Vorhanden (ausser 'Autogenerated')"
$report += "Sortiermodus: $SortMode"
$report += "===================================================="
$report += "ERGEBNISSE:"
$report += "===================================================="
$report += ""

if ($allFindings.Count -eq 0) { 
    $report += ">>> Keine relevanten Eintraege gefunden." 
}
else {
    foreach ($pdf in $pdfFiles) {
        $hits = $allFindings | Where-Object { $_.SourcePDF -eq $pdf.Name }
        if ($hits) {
            $report += ">>> Funde in: $($pdf.Name)  (TOTAL: $($hits.Count))"
            $report += "----------------------------------------------------"
            foreach ($hit in $hits) {
                $errorMsg = if ($hit.ErrorMessage) { $hit.ErrorMessage } else { "n.a." }
                
                $report += "Seite $($hit.Page) | User: $($hit.User) | Group: $($hit.Group) | $($hit.Time)"
                $report += "  Reason: '$($hit.Reason)' | Error Message: '$errorMsg'"
                if ($hit.Action) {
                    $report += "  Action: '$($hit.Action)'"
                }
                $report += ""
            }
        }
    }
}

$report | Out-File -FilePath $reportPath -Encoding UTF8
Write-Host ""
Write-Host "=============================================="
Write-Host "Analyse abgeschlossen!"
Write-Host "Report gespeichert unter:"
Write-Host $reportPath
Write-Host "=============================================="

do {
    $choice = Read-Host "Moechten Sie eine neue Analyse starten? (J/N)"
    if ($choice -match "^[Jj]") {
        & $MyInvocation.MyCommand.Definition
        break
    }
    elseif ($choice -match "^[Nn]") {
        Write-Host "Programm beendet."
        break
    }
    else {
        Write-Host "Ungueltige Eingabe. Bitte J oder N eingeben."
    }
} while ($true)