# iTextSharp-basierte PDF Analyse fuer ICPMH Audit Trails
# MSAT Reviewer - ICPMH Edition
# Y-Zeilen erst gruppieren, dann nach Spalten filtern

$ScriptPath = Split-Path -Parent $MyInvocation.MyCommand.Definition
Add-Type -Path (Join-Path $ScriptPath "itextsharp.dll")

# Custom Strategy Class
$customStrategyCode = @"
using System;
using System.Collections.Generic;
using iTextSharp.text.pdf.parser;

public class CoordinateTextExtractionStrategy : ITextExtractionStrategy
{
    public List<TextChunk> TextChunks = new List<TextChunk>();
    
    public void BeginTextBlock() { }
    public void EndTextBlock() { }
    
    public void RenderText(TextRenderInfo renderInfo)
    {
        string text = renderInfo.GetText();
        var baseline = renderInfo.GetBaseline();
        float x = baseline.GetStartPoint()[0];
        float y = baseline.GetStartPoint()[1];
        TextChunks.Add(new TextChunk(text, x, y));
    }
    
    public string GetResultantText() { return ""; }
    public void RenderImage(ImageRenderInfo renderInfo) { }
}

public class TextChunk
{
    public string Text { get; set; }
    public float X { get; set; }
    public float Y { get; set; }
    
    public TextChunk(string text, float x, float y)
    {
        Text = text;
        X = x;
        Y = y;
    }
}
"@

Add-Type -TypeDefinition $customStrategyCode -ReferencedAssemblies (Join-Path $ScriptPath "itextsharp.dll")

$TargetGroups = @("ICPMHAdmin", "ICPMHManager")

Write-Host "=============================================="
Write-Host " MSAT Reviewer - ICPMH Audit Trail Analyzer"
Write-Host " (Y-Zeilen gruppiert)"
Write-Host "=============================================="
Write-Host ""
Write-Host "Filter-Einstellungen:"
Write-Host "  - Groups: $($TargetGroups -join ', ')"
Write-Host "  - Reason: Muss vorhanden sein (ausser 'Autogenerated')"
Write-Host ""

$sortChoice = Read-Host "Sortieren nach Seitenzahl (S) oder User (U)?"
if ($sortChoice -match "^[Uu]") { $SortMode = "User" }
else { $SortMode = "Seitenzahl" }

$ATIN = Join-Path $ScriptPath "AT_IN"
if (-not (Test-Path $ATIN)) {
    Write-Host "AT_IN nicht gefunden. Bitte Ordner auswaehlen..."
    Add-Type -AssemblyName System.Windows.Forms
    $fbd = New-Object System.Windows.Forms.FolderBrowserDialog
    if ($fbd.ShowDialog() -eq "OK") { $ATIN = $fbd.SelectedPath } else { return }
} else {
    $confirm = Read-Host "AT_IN gefunden. PDFs dort analysieren? (J/N)"
    if ($confirm -notmatch "^[Jj]") {
        Add-Type -AssemblyName System.Windows.Forms
        $fbd = New-Object System.Windows.Forms.FolderBrowserDialog
        if ($fbd.ShowDialog() -eq "OK") { $ATIN = $fbd.SelectedPath } else { return }
    }
}

$pdfFiles = Get-ChildItem -Path $ATIN -Filter *.pdf
if (-not $pdfFiles) {
    Write-Host "Keine PDFs im Ordner. Beende..."
    return
}

$ATOUT = Join-Path $ScriptPath "AT_OUT"
if (-not (Test-Path $ATOUT)) { New-Item -Path $ATOUT -ItemType Directory | Out-Null }

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$reportPath = Join-Path $ATOUT "ICPMH_RE$timestamp.txt"
$UserName = $env:USERNAME

# PDF mit Koordinaten extrahieren
function Get-PdfTextChunks {
    param($pdfPath)
    $reader = New-Object iTextSharp.text.pdf.PdfReader -ArgumentList $pdfPath
    # OPTIMIERUNG: ArrayList statt Array += (bis zu 10x schneller bei vielen Seiten!)
    $allChunks = [System.Collections.ArrayList]::new()

    for ($i = 1; $i -le $reader.NumberOfPages; $i++) {
        $strategy = New-Object CoordinateTextExtractionStrategy
        [void][iTextSharp.text.pdf.parser.PdfTextExtractor]::GetTextFromPage($reader, $i, $strategy)

        foreach ($chunk in $strategy.TextChunks) {
            [void]$allChunks.Add([pscustomobject]@{
                Page = $i
                X = $chunk.X
                Y = $chunk.Y
                Text = $chunk.Text
            })
        }
    }

    $reader.Close()
    return $allChunks.ToArray()
}

# Gruppiere Chunks nach Y-Position (physische Zeilen)
function Group-ChunksByY {
    param($chunks, $yTolerance = 0.5)

    # OPTIMIERUNG: ArrayList für jede Y-Gruppe (verhindert += Array-Kopien)
    $yGroups = @{}

    foreach ($chunk in $chunks) {
        $y = $chunk.Y
        $foundGroup = $false

        # Suche existierende Y-Gruppe
        foreach ($existingY in $yGroups.Keys) {
            if ([Math]::Abs($y - $existingY) -lt $yTolerance) {
                [void]$yGroups[$existingY].Add($chunk)
                $foundGroup = $true
                break
            }
        }

        # Neue Gruppe erstellen (als ArrayList)
        if (-not $foundGroup) {
            $yGroups[$y] = [System.Collections.ArrayList]::new()
            [void]$yGroups[$y].Add($chunk)
        }
    }

    return $yGroups
}

# Retrospektive Footer-Bereinigung von Zelleninhalten
function Clean-FooterFromCell {
    param($cellText, $columnName)

    $cleaned = $cellText

    # User-Spalte: Entferne Footer-Datum am Ende (mit Trennzeichen)
    if ($columnName -eq "User") {
        # Entferne " ion Date : YYYY-MM-DD" (ion nicht Teil eines Wortes)
        $cleaned = $cleaned -replace "(?<!\w)ion\s+Date\s*:\s*\d{4}-\d{2}-\d{2}.*$", ""
        # Entferne " Date : YYYY-MM-DD" oder " Date:YYYY-MM-DD"
        $cleaned = $cleaned -replace "\s+Date\s*:\s*\d{4}-\d{2}-\d{2}.*$", ""
        # Fallback: Entferne Datum-Pattern am Ende (wenn durch Leerzeichen getrennt)
        $cleaned = $cleaned -replace "\s+\d{4}-\d{2}-\d{2}\s*$", ""
    }

    # Group-Spalte: Schneide nach bekannten Gruppennamen ab
    if ($columnName -eq "Group") {
        # Finde den ersten passenden Gruppennamen und schneide dort ab
        if ($cleaned -match "(ICPMHAdmin|ICPMHOperators|ICPMHManagers|ASnT)") {
            $cleaned = $matches[1]
        }
    }

    # Time-Spalte: Entferne alles NACH dem ersten GMT±HH:MM
    if ($columnName -match "Time") {
        if ($cleaned -match "(.*?GMT[+-]\d{2}:\d{2})") {
            $cleaned = $matches[1]
        }
    }

    # Error-Spalte: Entferne "Page X/Y" (mit oder ohne Leerzeichen)
    if ($columnName -match "Error") {
        $cleaned = $cleaned -replace "Page\s*\d+/\d+", ""
        $cleaned = $cleaned -replace "^\s*\d+/\d+\s*$", ""
    }

    return $cleaned.Trim()
}

# Parse alle Eintraege
function Parse-AuditEntries {
    param($chunks, $pdfName)
    
    Write-Host ""
    Write-Host "=== PARSING STARTEN ==="
    Write-Host "Chunks gesamt: $($chunks.Count)"

    # Bestimme Seitenzahl
    $totalPages = ($chunks | Select-Object -ExpandProperty Page -Unique | Measure-Object -Maximum).Maximum
    Write-Host "Seiten gesamt: $totalPages"

    # 1. Finde Header-Zeile (NUR AUF SEITE 1)
    $page1Chunks = $chunks | Where-Object { $_.Page -eq 1 }
    $yGroups = Group-ChunksByY -chunks $page1Chunks
    $headerY = $null

    foreach ($y in ($yGroups.Keys | Sort-Object -Descending)) {
        $yChunks = $yGroups[$y]
        $yText = ($yChunks | Sort-Object X | Select-Object -ExpandProperty Text) -join " "

        if ($yText -match "User" -and $yText -match "Group" -and
            $yText -match "Time" -and $yText -match "Category") {
            $headerY = $y
            Write-Host "Header gefunden bei Y=$([Math]::Round($headerY, 2)) (Seite 1)"
            break
        }
    }

    if (-not $headerY) {
        Write-Host "FEHLER: Kein Header gefunden auf Seite 1!"
        return @()
    }

    # 2. Extrahiere Spalten-X-Positionen aus Header (VON SEITE 1)
    $headerChunks = $page1Chunks | Where-Object { 
        [Math]::Abs($_.Y - $headerY) -lt 2.0 -and
        $_.Text -match "^(User|Group|Time|Succeeded|Category|Reason|Action|Error)"
    } | Sort-Object X
    
    if ($headerChunks.Count -lt 8) {
        Write-Host "FEHLER: Nur $($headerChunks.Count) Spalten gefunden!"
        return @()
    }
    
    $columns = @()
    foreach ($hc in $headerChunks) {
        $columns += [pscustomobject]@{ Name = $hc.Text; XStart = $hc.X; XEnd = 999 }
    }

    # Setze XEnd fuer jede Spalte (= Start der naechsten Spalte)
    for ($i = 0; $i -lt $columns.Count; $i++) {
        if ($i+1 -lt $columns.Count) {
            $columns[$i].XEnd = $columns[$i+1].XStart
        } else {
            $columns[$i].XEnd = 1000
        }
    }

    Write-Host "Spalten erkannt: $($columns.Count)"

    # 3. Finde Tabellenzeilen-Starts (UEBER ALLE SEITEN)
    # User-Eintrag markiert neue Tabellenzeile
    # OPTIMIERUNG: ArrayList statt Array += (viel schneller!)
    $tableRowStarts = [System.Collections.ArrayList]::new()
    $userCol = $columns[0]
    $groupCol = $columns[1]

    # OPTIMIERUNG: Cache Chunks nach Seite (verhindert wiederholte Where-Object Durchläufe)
    Write-Host "Bereite Seiten-Cache vor..."
    $chunksPerPage = @{}
    $pageYGroupsCache = @{}
    foreach ($chunk in $chunks) {
        if (-not $chunksPerPage.ContainsKey($chunk.Page)) {
            $chunksPerPage[$chunk.Page] = [System.Collections.ArrayList]::new()
        }
        [void]$chunksPerPage[$chunk.Page].Add($chunk)
    }

    for ($pageNum = 1; $pageNum -le $totalPages; $pageNum++) {
        # Verwende gecachte Chunks statt Where-Object
        $pageChunks = $chunksPerPage[$pageNum]
        if (-not $pageChunks) { continue }

        # Cache Y-Gruppen pro Seite
        if (-not $pageYGroupsCache.ContainsKey($pageNum)) {
            $pageYGroupsCache[$pageNum] = Group-ChunksByY -chunks $pageChunks
        }
        $pageYGroups = $pageYGroupsCache[$pageNum]

        foreach ($y in ($pageYGroups.Keys | Sort-Object -Descending)) {
            # Auf Seite 1: Ueberspringe Header-Bereich
            if ($pageNum -eq 1 -and $y -ge ($headerY - 5)) { continue }

            # Ueberspringe sehr niedrige Y (Footer-Bereich)
            if ($y -lt 50) { continue }

            $yChunks = @($pageYGroups[$y])

            # Suche in User-Spalte
            $userChunks = $yChunks | Where-Object { $_.X -ge $userCol.XStart -and $_.X -lt $userCol.XEnd }

            # Wenn User-Spalte gefuellt: Neue Tabellenzeile!
            if ($userChunks) {
                # Pruefe auch Group-Spalte zur Validierung
                $groupChunks = $yChunks | Where-Object { $_.X -ge $groupCol.XStart -and $_.X -lt $groupCol.XEnd }
                $groupText = ($groupChunks | Select-Object -ExpandProperty Text) -join ""

                if ($groupText -match "ICPMH") {
                    [void]$tableRowStarts.Add([pscustomobject]@{ Page=$pageNum; Y=$y })
                }
            }
        }
    }

    # Sortiere: Erst nach Page, dann nach Y (absteigend)
    $tableRowStarts = $tableRowStarts | Sort-Object Page, @{Expression="Y"; Descending=$true}
    Write-Host "Tabellenzeilen erkannt: $($tableRowStarts.Count)"
    
    if ($tableRowStarts.Count -eq 0) {
        Write-Host "FEHLER: Keine Tabellenzeilen gefunden!"
        return @()
    }
    
    # 4. Fuer jede Tabellenzeile: Extrahiere Zellen (MULTI-PAGE)
    # OPTIMIERUNG: ArrayList statt Array
    $entries = [System.Collections.ArrayList]::new()

    Write-Host "Extrahiere Zellinhalte..."
    for ($i = 0; $i -lt $tableRowStarts.Count; $i++) {
        $currentRow = $tableRowStarts[$i]
        $nextRow = if ($i+1 -lt $tableRowStarts.Count) { $tableRowStarts[$i+1] } else { $null }

        # OPTIMIERUNG: Sammle Chunks aus Cache statt Where-Object auf allen Chunks
        $rowChunks = [System.Collections.ArrayList]::new()
        if ($nextRow) {
            # Fall 1: Es gibt eine nächste Zeile
            if ($currentRow.Page -eq $nextRow.Page) {
                # Gleiche Seite: Einfacher Y-Bereich (verwende gecachte Page-Chunks)
                foreach ($chunk in $chunksPerPage[$currentRow.Page]) {
                    if ($chunk.Y -le $currentRow.Y -and $chunk.Y -gt $nextRow.Y) {
                        [void]$rowChunks.Add($chunk)
                    }
                }
            } else {
                # Mehrere Seiten (verwende gecachte Page-Chunks)
                for ($p = $currentRow.Page; $p -le $nextRow.Page; $p++) {
                    if (-not $chunksPerPage.ContainsKey($p)) { continue }

                    foreach ($chunk in $chunksPerPage[$p]) {
                        if ($p -eq $currentRow.Page) {
                            # Start-Seite: Ab currentRow.Y nach unten
                            if ($chunk.Y -le $currentRow.Y -and $chunk.Y -gt 50) {
                                [void]$rowChunks.Add($chunk)
                            }
                        } elseif ($p -eq $nextRow.Page) {
                            # End-Seite: Von oben bis nextRow.Y
                            if ($chunk.Y -gt $nextRow.Y) {
                                [void]$rowChunks.Add($chunk)
                            }
                        } else {
                            # Zwischenseite: Alles außer Header/Footer
                            if ($chunk.Y -lt 500 -and $chunk.Y -gt 50) {
                                [void]$rowChunks.Add($chunk)
                            }
                        }
                    }
                }
            }
        } else {
            # Fall 2: Letzte Zeile im Dokument (verwende gecachte Page-Chunks)
            for ($p = $currentRow.Page; $p -le $totalPages; $p++) {
                if (-not $chunksPerPage.ContainsKey($p)) { continue }

                foreach ($chunk in $chunksPerPage[$p]) {
                    if ($p -eq $currentRow.Page) {
                        if ($chunk.Y -le $currentRow.Y) {
                            [void]$rowChunks.Add($chunk)
                        }
                    } else {
                        if ($chunk.Y -gt 50 -and $chunk.Y -lt 500) {
                            [void]$rowChunks.Add($chunk)
                        }
                    }
                }
            }
        }

        $entry = [ordered]@{
            Page         = $currentRow.Page
            User         = ""
            Group        = ""
            Time         = ""
            Succeeded    = ""
            Category     = ""
            Reason       = ""
            Action       = ""
            ErrorMessage = ""
            SourcePDF    = $pdfName
        }
        
        # Extrahiere jede Spalte
        for ($c = 0; $c -lt $columns.Count; $c++) {
            $col = $columns[$c]

            # Finde Chunks in dieser Spalte (zwischen XStart und XEnd)
            $colChunks = $rowChunks | Where-Object {
                $_.X -ge $col.XStart -and $_.X -lt $col.XEnd
            } | Sort-Object Page, @{Expression="Y"; Descending=$true}, X

            # Join ohne Leerzeichen und normalisiere dann Whitespace
            $cellText = ($colChunks | Select-Object -ExpandProperty Text) -join ""
            $cellText = $cellText -replace "\s+", " "  # Mehrfache Leerzeichen durch eines ersetzen
            $cellText = $cellText.Trim()

            # RETROSPEKTIVE BEREINIGUNG: Nur bei der LETZTEN Tabellenzeile
            $finalCellText = $cellText
            if ($i -eq ($tableRowStarts.Count - 1)) {
                $finalCellText = Clean-FooterFromCell -cellText $cellText -columnName $col.Name
            }

            # Zuordnung nach Spaltenname
            if ($col.Name -eq "User") { $entry.User = $finalCellText }
            elseif ($col.Name -eq "Group") { $entry.Group = $finalCellText }
            elseif ($col.Name -match "Time") { $entry.Time = $finalCellText }
            elseif ($col.Name -eq "Succeeded") { $entry.Succeeded = $finalCellText }
            elseif ($col.Name -eq "Category") { $entry.Category = $finalCellText }
            elseif ($col.Name -eq "Reason") { $entry.Reason = $finalCellText }
            elseif ($col.Name -eq "Action") { $entry.Action = $finalCellText }
            elseif ($col.Name -match "Error") { $entry.ErrorMessage = $finalCellText }
        }

        # OPTIMIERUNG: .Add() statt +=
        [void]$entries.Add([pscustomobject]$entry)
    }

    return $entries.ToArray()
}

# Hauptlogik
Write-Host "Analysiere PDFs..."
# OPTIMIERUNG: ArrayList statt Array
$allFindings = [System.Collections.ArrayList]::new()

foreach ($pdf in $pdfFiles) {
    Write-Host ""
    Write-Host "======================================"
    Write-Host "PDF: $($pdf.Name)"
    Write-Host "======================================"

    $chunks = Get-PdfTextChunks -pdfPath $pdf.FullName
    $entries = Parse-AuditEntries -chunks $chunks -pdfName $pdf.Name

    Write-Host "Gefundene Eintraege: $($entries.Count)"

    # DEBUG: Zeige erste 3 Eintraege
    if ($entries.Count -gt 0) {
        Write-Host ""
        Write-Host "DEBUG: Erste 3 Eintraege zur Pruefung:"
        for ($i = 0; $i -lt [Math]::Min(3, $entries.Count); $i++) {
            $e = $entries[$i]
            Write-Host "  [$($i+1)] User='$($e.User)' | Group='$($e.Group)' | Reason='$($e.Reason)'"
        }
        Write-Host ""
    }

    foreach ($e in $entries) {
        $groupMatch = $false
        foreach ($tg in $TargetGroups) {
            if ($e.Group -like "*$tg*") { $groupMatch = $true; break }
        }

        $reasonValid = (-not [string]::IsNullOrWhiteSpace($e.Reason)) -and
                       ($e.Reason -ne "Autogenerated")

        if ($groupMatch -and $reasonValid) {
            # OPTIMIERUNG: .Add() statt +=
            [void]$allFindings.Add($e)
        }
    }

    $pdfHits = ($allFindings | Where-Object { $_.SourcePDF -eq $pdf.Name }).Count
    Write-Host "Relevante Findings: $pdfHits"
}

Write-Host ""
Write-Host "======================================"
Write-Host "Gesamtanzahl Findings: $($allFindings.Count)"
Write-Host "======================================"

if ($SortMode -eq "User") {
    $allFindings = $allFindings | Sort-Object User, Time
}
else {
    $allFindings = $allFindings | Sort-Object Page, Time
}

# Report schreiben
$report = @()
$report += "----------------------------------------------------"
$report += " MSAT Review - Analysebericht (ICPMH)"
$report += "----------------------------------------------------"
$report += "Benutzer: $UserName"
$report += "Datum:    $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$report += ""
$report += "Analysierte PDFs: [$($pdfFiles.Name -join ', ')]"
$report += "TOTAL Findings Overall: $($allFindings.Count)"
$report += ""
$report += "Filter-Kriterien:"
$report += "  - Groups: $($TargetGroups -join ', ')"
$report += "  - Reason: Vorhanden (ausser 'Autogenerated')"
$report += "Sortiermodus: $SortMode"
$report += "===================================================="
$report += "ERGEBNISSE:"
$report += "===================================================="
$report += ""

if ($allFindings.Count -eq 0) { 
    $report += ">>> Keine relevanten Eintraege gefunden." 
}
else {
    foreach ($pdf in $pdfFiles) {
        $hits = $allFindings | Where-Object { $_.SourcePDF -eq $pdf.Name }
        if ($hits) {
            $report += ">>> Funde in: $($pdf.Name)  (TOTAL: $($hits.Count))"
            $report += "----------------------------------------------------"
            foreach ($hit in $hits) {
                $errorMsg = if ($hit.ErrorMessage) { $hit.ErrorMessage } else { "n.a." }
                
                $report += "Seite $($hit.Page) | User: $($hit.User) | Group: $($hit.Group) | $($hit.Time)"
                $report += "  Reason: '$($hit.Reason)' | Error Message: '$errorMsg'"
                if ($hit.Action) {
                    $report += "  Action: '$($hit.Action)'"
                }
                $report += ""
            }
        }
    }
}

$report | Out-File -FilePath $reportPath -Encoding UTF8
Write-Host ""
Write-Host "=============================================="
Write-Host "Analyse abgeschlossen!"
Write-Host "Report gespeichert unter:"
Write-Host $reportPath
Write-Host "=============================================="

do {
    $choice = Read-Host "Moechten Sie eine neue Analyse starten? (J/N)"
    if ($choice -match "^[Jj]") {
        & $MyInvocation.MyCommand.Definition
        break
    }
    elseif ($choice -match "^[Nn]") {
        Write-Host "Programm beendet."
        break
    }
    else {
        Write-Host "Ungueltige Eingabe. Bitte J oder N eingeben."
    }
} while ($true)